# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_AXI_GammaCorrection_0_0_1/design_1_AXI_GammaCorrection_0_0.xci
# IP: The module: 'design_1_AXI_GammaCorrection_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_AXI_GammaCorrection_0_0_1/xdc/AXI_GammaCorrection.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_AXI_GammaCorrection_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_AXI_GammaCorrection_0_0_1/design_1_AXI_GammaCorrection_0_0.xci
# IP: The module: 'design_1_AXI_GammaCorrection_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_AXI_GammaCorrection_0_0_1/xdc/AXI_GammaCorrection.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_AXI_GammaCorrection_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
