# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/design_1_MIPI_D_PHY_RX_0_0.xci
# IP: The module: 'design_1_MIPI_D_PHY_RX_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_scnn_refclk/ila_scnn_refclk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_scnn_refclk || ORIG_REF_NAME==ila_scnn_refclk} -quiet] -quiet

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_refclk/ila_sfen_refclk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_sfen_refclk || ORIG_REF_NAME==ila_sfen_refclk} -quiet] -quiet

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_rxclk/ila_sfen_rxclk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_sfen_rxclk || ORIG_REF_NAME==ila_sfen_rxclk} -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_scnn_refclk/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_scnn_refclk || ORIG_REF_NAME==ila_scnn_refclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_scnn_refclk/ila_scnn_refclk_ooc.xdc

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_refclk/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_sfen_refclk || ORIG_REF_NAME==ila_sfen_refclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_refclk/ila_sfen_refclk_ooc.xdc

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_rxclk/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_sfen_rxclk || ORIG_REF_NAME==ila_sfen_rxclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_rxclk/ila_sfen_rxclk_ooc.xdc

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/MIPI_DPHY_Receiver.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_MIPI_D_PHY_RX_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/MIPI_DPHY_Receiver_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_MIPI_D_PHY_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/MIPI_DPHY_Receiver_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_MIPI_D_PHY_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/design_1_MIPI_D_PHY_RX_0_0.xci
# IP: The module: 'design_1_MIPI_D_PHY_RX_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_scnn_refclk/ila_scnn_refclk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_scnn_refclk || ORIG_REF_NAME==ila_scnn_refclk} -quiet] -quiet

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_refclk/ila_sfen_refclk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_sfen_refclk || ORIG_REF_NAME==ila_sfen_refclk} -quiet] -quiet

# IP: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_rxclk/ila_sfen_rxclk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_sfen_rxclk || ORIG_REF_NAME==ila_sfen_rxclk} -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_scnn_refclk/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_scnn_refclk || ORIG_REF_NAME==ila_scnn_refclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_scnn_refclk/ila_scnn_refclk_ooc.xdc

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_refclk/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_sfen_refclk || ORIG_REF_NAME==ila_sfen_refclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_refclk/ila_sfen_refclk_ooc.xdc

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_rxclk/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_sfen_rxclk || ORIG_REF_NAME==ila_sfen_rxclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/ila_sfen_rxclk/ila_sfen_rxclk_ooc.xdc

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/MIPI_DPHY_Receiver.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_MIPI_D_PHY_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/MIPI_DPHY_Receiver_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_MIPI_D_PHY_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ernesto/workstation/Systems_Cleanbot/hardware/PiCAM/PiCAM.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0_1/hdl/MIPI_DPHY_Receiver_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_MIPI_D_PHY_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
